package types

type UNTERGLIEDERUNG int

const (
    UG_WOE UNTERGLIEDERUNG = 1
    UG_JUFFI UNTERGLIEDERUNG = 2
    UG_PFADI UNTERGLIEDERUNG = 3
    UG_ROVER UNTERGLIEDERUNG = 4
    UG_STAVO UNTERGLIEDERUNG = 5
)

type TAETIGKEIT int

const (
    TG_LEITER TAETIGKEIT = 6
    TG_MITGLIED TAETIGKEIT = 1
    TG_PASSIV TAETIGKEIT = 39
    TG_KURAT TAETIGKEIT = 1011
)

type MITGLIEDTYPEID string

const (
    MITGLIED MITGLIEDTYPEID = "MITGLIED"
    NICHTMITGLIED MITGLIEDTYPEID = "Nicht-Mitglied"
)

type MITGLIEDSTATUSID string

const (
    AKTIV MITGLIEDSTATUSID = "AKTIV"
)
